name = "hotoke-api"
compatibility_date = "2024-09-13"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "hotoke"
id = "hotoke"
preview_id = "hotoke"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hotoke"
database_id = "hotoke"

# [ai]
# binding = "AI"